// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/cf-watch/watch (interfaces: File)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	filetree "github.com/pivotal-cf/cf-watch/filetree"
	os "os"
)

// Mock of File interface
type MockFile struct {
	ctrl     *gomock.Controller
	recorder *_MockFileRecorder
}

// Recorder for MockFile (not exported)
type _MockFileRecorder struct {
	mock *MockFile
}

func NewMockFile(ctrl *gomock.Controller) *MockFile {
	mock := &MockFile{ctrl: ctrl}
	mock.recorder = &_MockFileRecorder{mock}
	return mock
}

func (_m *MockFile) EXPECT() *_MockFileRecorder {
	return _m.recorder
}

func (_m *MockFile) Basename() string {
	ret := _m.ctrl.Call(_m, "Basename")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockFileRecorder) Basename() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Basename")
}

func (_m *MockFile) Children() []filetree.File {
	ret := _m.ctrl.Call(_m, "Children")
	ret0, _ := ret[0].([]filetree.File)
	return ret0
}

func (_mr *_MockFileRecorder) Children() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Children")
}

func (_m *MockFile) Close() error {
	ret := _m.ctrl.Call(_m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockFileRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}

func (_m *MockFile) Mode() (os.FileMode, error) {
	ret := _m.ctrl.Call(_m, "Mode")
	ret0, _ := ret[0].(os.FileMode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFileRecorder) Mode() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Mode")
}

func (_m *MockFile) Read(_param0 []byte) (int, error) {
	ret := _m.ctrl.Call(_m, "Read", _param0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFileRecorder) Read(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Read", arg0)
}

func (_m *MockFile) Size() (int64, error) {
	ret := _m.ctrl.Call(_m, "Size")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFileRecorder) Size() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Size")
}
