// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/pivotal-cf/cf-watch/watch (interfaces: Tree)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	filetree "github.com/pivotal-cf/cf-watch/filetree"
)

// Mock of Tree interface
type MockTree struct {
	ctrl     *gomock.Controller
	recorder *_MockTreeRecorder
}

// Recorder for MockTree (not exported)
type _MockTreeRecorder struct {
	mock *MockTree
}

func NewMockTree(ctrl *gomock.Controller) *MockTree {
	mock := &MockTree{ctrl: ctrl}
	mock.recorder = &_MockTreeRecorder{mock}
	return mock
}

func (_m *MockTree) EXPECT() *_MockTreeRecorder {
	return _m.recorder
}

func (_m *MockTree) New(_param0 string) (filetree.File, error) {
	ret := _m.ctrl.Call(_m, "New", _param0)
	ret0, _ := ret[0].(filetree.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockTreeRecorder) New(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "New", arg0)
}
